title: Shiya Wang
position: Postdoctoral Fellow
affiliation: Columbia Business School
email: sw2876 (at) columbia.edu

avatar: ./images/sw_headshot.min.jpg
favicon: ./images/sw_headshot.min.jpg

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
